spring:
  application:
    name: OrderApp
  datasource:
    url: jdbc:h2:mem:orderApp;LOCK_TIMEOUT=10000
    driver-class-name: org.h2.Driver
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console